export let ModelsNames: {
  user: string;
  job: string;
  partner: string;
  product: string;
  smallParagraph: string;
  childService: string;
  parentService: string;
  serviceFeature: string;
  standAlone: string;
  requestOffer: string;
  jobForm: string;
  contactUs: string;
  pricingStep: string;
  pricingCategory: string;
  pricingService: string;
  pricingTeamMember: string;
  pricingHistory: string;
};
(function (ModelsNames) {
  ModelsNames["user"] = "user";
  ModelsNames["standAlone"] = "stand-alone";
  ModelsNames["childService"] = "child-service";
  ModelsNames["parentService"] = "parent-service";
  ModelsNames["serviceFeature"] = "service-feature";
  ModelsNames["product"] = "product";
  ModelsNames["partner"] = "partner";
  ModelsNames["job"] = "job";
  ModelsNames["jobForm"] = "job-form";
  ModelsNames["requestOffer"] = "request-offer";
  ModelsNames["contactUs"] = "contact-us";
  ModelsNames["smallParagraph"] = "small-paragraph";
  ModelsNames["pricingHistory"] = "pricing-history";
  ModelsNames["pricingService"] = "pricing-service";
  ModelsNames["pricingCategory"] = "pricing-category";
  ModelsNames["pricingStep"] = "pricing-step";
  ModelsNames["pricingTeamMember"] = "pricing-team-member";
  ModelsNames["pricingFeature"] = "pricing-feature";
})((ModelsNames = exports.ModelsNames || (exports.ModelsNames = {})));
