import { Role } from "../types/role.enum";
const allRoles = Object.keys(Role);

export const authRoles = {
  standAlone: {
    setAbout: [Role.admin],
    setVision: [Role.admin],
    setMission: [Role.admin],
    getAbout: [],
    getVision: [],
    getMission: [],
  },
  auth: {
    register: [],
    login: [],
    forgetPassword: [],
    me: allRoles,
    changePassword: allRoles,
    resetPassword: allRoles,
  },
  user: {
    findAll: [Role.admin],
    findOne: [Role.admin],
    update: [Role.user, Role.admin],
  },
  contactUs: {
    findAll: [Role.admin],
    findOne: [Role.admin],
    create: [],
  },
  smallParagraphs: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  requestOffer: {
    findAll: [Role.admin],
    findOne: [Role.admin],
    create: [],
  },
  job: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  jobForm: {
    findAll: [Role.admin],
    findOne: [Role.admin],
    create: [],
  },
  product: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  partner: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  parentService: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  childService: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  serviceFeature: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  pricingStep: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  pricingCategory: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  pricingService: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  pricingTeamMember: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  pricingFeature: {
    findAll: [],
    findOne: [],
    create: [Role.admin],
    update: [Role.admin],
    delete: [Role.admin],
  },
  pricingHistory: {
    findAll: [Role.user, Role.admin],
    findOne: [Role.user, Role.admin],
    create: [],
  },
};
